name: Unit Testing

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    test:
        name: TYPO3
        runs-on: ubuntu-latest
        strategy:
          matrix:
            variants: [ { typo3: 12.4, php: 8.1 }, { typo3: 12.4, php: 8.4 }, { typo3: 13.4, php: 8.2 }, { typo3: 13.4, php: 8.4 } ]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: Build/Test/runTests.sh -s composerInstall -t ${{ matrix.variants.typo3 }} -p ${{ matrix.variants.php }}

            - name: Run unit tests
              run: Build/Test/runTests.sh -s unit -p ${{ matrix.variants.php }}
